### ISSUE TITLE
Hi question about reactProgram() parameters

### ISSUE THREAD

**Issue by rluiten** [andrejewski/raj-react#19]
I am trying to understand why you pass Component as a parameter to `reactProgram` rather than just extend React.Component ? The only benefit I can think of is that you may have a use case that supplies something other than the common React.Component as the parameter, do you have such an example ?

I am the person who posted on your Raj 1.0 thread https://www.reddit.com/r/javascript/comments/8st3bi/raj_the_elm_architecture_for_javascript_releases/ with the typescript version just to give you context.

**Comment by andrejewski** [comment]
Reasons include:

- Not wanting to have React as a dependency, `raj-react` supports both React 15 and 16 and most likely 17 and potentially older versions as well as it doesn't do anything crazy.
- The use case of someone wanting to extend React.Component themselves and use a custom Component class as their root element perhaps with some lifecycle hooks specified.
- Supporting Preact.Component other projects that have React API compatibility.

This is a small typing inconvenience since you will only call `raj-react` once per app. I think it gives the developer much more control and for me as a maintainer it is easier to maintain.

**Comment by rluiten** [comment]
All good points, I asked because I suspect you had reasons.
